set_13_18 = [
    "so fleek",
    "so BAE",
    "FML",
    "I die",
    "Squad",
    "Hook up",
    "flex",
    "school",
    "homework",
    "haha",
    "lol",
    "awesome",
    "single",
    ':D',
    ';D',
    "ugh",
    "sucks",
    ':P',
    "bored",
    "lovee",
    "bestfriend",
    "boyfriend",
    "miss",
    "wanna",
    "relationship",
    "hehe",
    "prom",
    "homecoming",
    "status",
    "bleh",
    '<3']

set_19_22 = [
    "wanna",
    "semester",
    "studying",
    "21st",
    "shit",
    "exam",
    "campus",
    "classes",
    "apartement",
    "college",
    "fuck",
    "fucked",
    "drom",
    "library"]

set_23_29 = [
    "Booty call",
    "weak",
    "fit",
    "Let's pootle",
    "Chinay",
    "Laura Ashley lager",
    "Lady petrol",
    "Lady petrol",
    "sweet",
    "safe",
    "dope",
    "word",
    "gas",
    "wack",
    "It's snap, crackle and pop",
    "at work",
    "interview",
    "office",
    "beer",
    "drinks",
    "enjoying",
    "laundry",
    "apartment",
    "wine",
    "blessed",
    "wedding",
    "days off",
    "new place",
    "house",
    "uni",
    "love"]

set_30_65 = [
    "Take a chill pill",
    "Well fit",
    "wicked",
    "wazzok",
    "mental",
    "minging",
    "mofo",
    "trollied",
    "coolio",
    "gear",
    "get off with",
    "licking out",
    "Ugandan discussions",
    "Really hung",
    "fit","square",
    "L-7",
    "Splitsville",
    "Tirra lirra, by the river",
    "Sluttish",
    "Fab gear",
    "daughter",
    "son",
    "grand daughter",
    "grandson",
    "country",
    "freedom",
    "friends",
    "family",
    "my kids",
    "my son",
    "my daughter",
    "prayer",
    "for a lifetime",
    "proud",
    "husband",
    "wife",
    "niece",
    "veterans",
    "god",
    "pray"]
