""" A list contains the query words to search for """
mylist = [  "cancer",
            "tumor",
            "leukemia",
            "neuroblastoma",
            "paraganglioma",
            "retinoblastoma",
            "astrocytomas",
            "retinoblastoma",
            "lymphoma",
            "melanoma",
            "syöpä",
            "kasvain",
            "säteily",
            "hoito",
            "kuolla",
            "malignant",  
            ## Refers to a tumor that is cancerous
            "metastasis", 
            ## Cancer spreading
            "oncology",   
            ## Study of cancer 
            "oncologist",
            "pathologist",
            ## Refers to cells that have the potential to become cancerous
            "precancerous",
            ## A type of cancer
            "sarcoma",
            "telemedicine",
            "healthcare",
            "chemotherapy",
            "chemo",
            "radiation",
            "hormone therapy",
            "mammogram",
            "kræft",
            "kreft",
            "carcino",
            "lymphom",
            "biopsy",
            "biopsies",
            "melano",
            "sarcoma",
            "dysplasia",
            "mammogr",
            "maligna",
            "metasta",
            # "PET scan",
            "ablate",
            "ablation",

            #### Finnish cancer foundation 
            "Adenokarsinooma",
            "Adenomatoosi",
            "Adenooma",
            "Adjuvanttihoito",
            "Aflatoksiini",
            "Akustikusneurinooma",
            "Akuutti leukemia",
            "Alfafetoproteiini",
            "Alkyloiva aine",
            "Ameloblastooma",
            "Anaplastinen",
            "Anastomoosi",
            "Anatomia",
            "Androgeeni",
            "Angiosarkooma",
            "Annossuunnittelu",
            "Antiandrogeenit",
            "Antiangiogeeninen hoito",
            "Antiemeetti",
            "Antiestrogeenit",
            "Antigeeni",
            "Antihormoni",
            "Antimetaboliitti",
            "Antioksidantit",
            "Anuria",
            "Apoptoosi",
            "Astrosytooma",
            "Avanne",
            "Barrettin limakalvo",
            "Basaliooma",
            "Benigni",
            "Betatroni",
            "Bilateraalinen",
            "Biologinen hoito",
            "Biopsia",
            "Blasti",
            "Boorineutronisädehoito",
            "Bowenin tauti",
            "Brakyterapia",
            "Breslow’n luokitus",
            "Caecum",
            "Clarkin luokitus",
            "Colitis ulcerosa",
            # "DCIS",
            "Dermatofibrooma",
            "Dermatofibrosarkooma",
            "Desmoidi",
            "Duktaalinen karsinooma",
            "Dysgerminooma",
            # "Edeema",
            "Ektomia",
            "Elossaololuku",
            "Elossaolotutkimus",
            "Embryonaalinen karsinooma",
            "Ependymooma",
            "aivokasvain",
            "Epidermoidikarsinooma",
            "Epstein–Barrin virus",
            "Etäpesäke",
            "Metastaasi",
            "Ewingin sarkooma",
            # "FAP",
            "Follikulaarinen karsinooma",
            "Fotonihoito",
            "Fraktioitu sädehoito",
            "Gastrektomia",
            "Geenihoito",
            # "GIST",
            "Gleasonin luokitus",
            "gynecomastia",
            "Helikobakteeri",
            "Hemangiosarkooma",
            "Hematemeesi",
            "Hepatoblastooma",
            "Hodgkinin lymfooma",
            "Hormonihoito",
            "Hyperfraktioitu sädehoito",
            "Hypernefrooma",
            "Hürthlensolukarsinooma",
            "Immunohistochemical study",
            "Immuunihoito",
            "Intensiteettimuokattu sädehoito",
            "Interstitiaalinen sädehoito",
            "Intestinaalinen karsinooma",
            "Intraduktaalinen karsinooma",
            "Intrakavitaarinen sädehoito",
            "Ionisoiva säteily",
            "Itusolukasvaimet",
            "Jaksotettu sädehoito",
            "Karsinooma",
            "Karvasoluleukemia",
            "Kemosädehoito",
            "Kemoterapia",
            "karsinooma",
            "Lymfooma",
            "Magneettikuvaus",
            "Maligni",
            "Mammakarsinooma",
            "Manttelihoito",
            "Meningeooma",
            "Merkelinsolukarsinooma",
            "Onkologi",
            "Oligodendrogliooma",
            "Osteoklastooma",
            "syöpäalttius",
            "Pintasyöpä",
            "Plasmosytooma",
            "Primaarikasvain",
            "Sarkooma",
            "Sertolinsolukasvain",
            "sädehoito",
            "TNM-luokitus",
            "Tuumori",
            "Tymooma",
            "Verisyöpä",


        ### SPECIFIC CANCER KEYWORDS
        "bone neoplasm",
        "osteosarcoma",
        "ewing tumor",
        "fibrosarcoma",
        "histiocytoma",
        "chordoma",
        "gastrointestinal",
        "tract cancer",
        "colorectal",
        "colon cancer",
        "stomach adenocarcinoma",
        "lymphoma",
        "carcinoid",
        "carcinoma",
        "breast adenocarcinoma",
        "carcinoma in situ",
        "sarcoma",
        # "SCLC",
        # "NSCLC",
        "ductal",
        "medullary",
        "phyllodes",
        "angiosarcoma",
        "mucinous",
        "colloid",
        "nipple termed Paget",
        "lobular",
        "LCIS",
        "squamous cell carcinomas",
        "large cell carcinomas",
        "bronchial carcinoids",
        "lymphoma",
        "melanoma",
        "basal",
        "dermatology",
        "moles",
        "oral cavity",
        "pharynx",
        "larynx",
        "neoplasm",
        "acoustic Neuroma",
        "astrocytoma",
        "chordoma",
        "CNS Lymphoma",
        "fibrocystic",
        "craniopharyngioma",
        "medulloblastoma",
        "meningioma",
        "metastatic Brain Tumors",
        "oligodendroglioma",
        "pituitary Tumors",
        "primitive Neuroectodermal",
        # "PNET",
        "schwannoma",
        "bone neoplasm",
        "osteosarcoma",
        "ewing tumor",
        "fibrosarcoma",
        "histiocytoma",
        "chordoma",
        "neuroblastoma",
        "wilms tumor",
        "osteosarcoma",
        "retinoblastoma",
        "pediatric",
        "XRCC1",
        # "EGFR",
        # "KRas",
        # "P53",
        "BRCA1",
        "benign",


        ## Survivor
        "cancer survivor",
        "syövän selviytyjä",
        "kanker overlevende",
        "kræft overlevende",
        "kreft overlevende",
        "cancer överlevare",
        "пострадавший от рака"
            ]

### Specific cancer types keywords
## From: https://www.cancer.gov/types
stomach=[
    "stomach",
    "vatsa",
    "gastric",
    "digestive",
    "gastrointestinal",
    "tract Cancer",
    "colorectal",
    "colon",
    "stomach adenocarcinoma",
    "lymphoma",
    "carcinoid"
]

breast=[
    "breast",
    "rinta",
    "carcinoma",
    "breast adenocarcinoma",
    "carcinoma in situ",
    "sarcoma",
    "BRCA1",
    "ductal",
    "medullary",
    "phyllodes",
    "angiosarcoma",
    "mucinous",
    "colloid",
    "nipple termed Paget",
    "lobular",
    "LCIS",
    "breastcancer",
    "tits",
    "boobs"
    "situ",
    "nipple",
    "nipples"
]

lung=[
    "lung",
    "keuhko",
    "SCLC",
    "NSCLC",
    "squamous cell carcinomas",
    "large cell carcinomas",
    "bronchial carcinoids"
]

skin=[
    "skin",
    "iho",
    "lymphoma",
    "melanoma",
    "basal",
    "dermatology",
    "melanoma",
    "moles"
]

blood=[
    "leukemia",
    "veri",
    "leucocythaemia",
    "leucocythaemias",
    "leucocythemia",
    "leucocythemia",
    "hematologic",
    "blood"
]

head_neck=[
    "neoplasm",
    "pään",
    "kaulan",
    "head",
    "neck",
    "oral cavity",
    "pharynx",
    "larynx"
]

brain=[
    "brain",
    "aviot",
    "acoustic Neuroma",
    "astrocytoma",
    "chordoma",
    "CNS Lymphoma",
    "craniopharyngioma",
    "medulloblastoma",
    "meningioma",
    "metastatic Brain Tumors",
    "oligodendroglioma",
    "pituitary Tumors",
    "primitive Neuroectodermal",
    "PNET",
    "schwannoma"
]

bone=[
    "bone",
    "luu",
    "bone neoplasm",
    "osteosarcoma",
    "ewing tumor",
    "fibrosarcoma",
    "histiocytoma",
    "chordoma"
]

pediatric=[
    "pediatric",
    "childhood",
    "child",
    "kid",
    "neuroblastoma",
    "wilms tumor",
    "osteosarcoma",
    "retinoblastoma"]